

export const ActionTypes={
    FETCH_PRODUCTS:'FETCH_PRODUCTS',
    SET_PRODUCTS:"SET_PRODUCTS",
    SELECT_PRODUCT:"SELECT_PRODUCT",
    REMOVE_SELECT_PRODUCTS:"REMOVE_SELECT_PRODUCTS",
    SET_USER:'SET_USER',
};